### ISSUE TITLE
AdColony [*** ERROR ***] : Cannot start AdColony; configuration mechanism dictates only one app ID can be used during a session.

### ISSUE THREAD

**Issue by halfdevil** [AdColony/AdColony-iOS-SDK#51]
Getting this error while using AdColony mediation with Google Mobile Ads new Rewarded API. This issue is occurring while caching rewarded ads with new APIs.

**Comment by raptos** [comment]
#49

**Comment by superjd** [comment]
Are you still facing this issue? can you send a mail to support@adcolony.com with more details.

**Comment by superjd** [comment]
No response.
