### ISSUE TITLE
AdColony calles UI API on background thread on iOS 13

### ISSUE THREAD

**Issue by iDevid** [AdColony/AdColony-iOS-SDK#53]
This is the stacktrace from my application running iOS 13:
2019-06-25 12:00:53.285910+0200 AppName[1036:90512] [reports] Main Thread Checker: UI API called on a background thread: -[UIViewController init]
PID: 1036, TID: 90512, Thread name: AdColony Worker, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   AppName                          0x00000001032b9498 -[ADCBrowser initWithDict:] + 76
5   AppName                          0x0000000103274540 -[ADCSystemAPI prepareBrowser:] + 484
6   AppName                          0x0000000103283ad0 -[ADCNativeLayer dispatchMessage:] + 600
7   AppName                          0x0000000103283800 -[ADCNativeLayer dispatchMessages:] + 284
8   AppName                          0x00000001032935d0 -[ADCJSCoreModule pumpMessages:] + 592
9   AppName                          0x0000000103283120 -[ADCNativeLayer moduleUpdate] + 312
10  Foundation                          0x00000001b25124d0 __NSFireTimer + 68
11  CoreFoundation                      0x00000001b287085c 56AA397F-A19A-319F-85D2-C47F84B01D4D + 706652
12  CoreFoundation                      0x00000001b2870594 56AA397F-A19A-319F-85D2-C47F84B01D4D + 705940
13  CoreFoundation                      0x00000001b286fc3c 56AA397F-A19A-319F-85D2-C47F84B01D4D + 703548
14  CoreFoundation                      0x00000001b286ab0c 56AA397F-A19A-319F-85D2-C47F84B01D4D + 682764
15  CoreFoundation                      0x00000001b286a07c CFRunLoopRunSpecific + 480
16  Foundation                          0x00000001b23d8774 F3AFEA10-23D4-32E2-8BEC-BACBE3EF9631 + 34676
17  AppName                          0x00000001032c05b4 -[AdColony setupWorkerThread] + 588
18  Foundation                          0x00000001b23d7404 F3AFEA10-23D4-32E2-8BEC-BACBE3EF9631 + 29700
19  Foundation                          0x00000001b2511488 F3AFEA10-23D4-32E2-8BEC-BACBE3EF9631 + 1315976
20  libsystem_pthread.dylib             0x00000001b3119c4c _pthread_start + 132
21  libsystem_pthread.dylib             0x00000001b3121c50 thread_start + 8

**Comment by superjd** [comment]
Thanks for reporting, we are aware of this and will have a fix, we do evaluate iOS13 betas when they get released.

**Comment by romankravets** [comment]
@superjd Hi, do you have any updates on this ?

**Comment by thomasmso** [comment]
Are there any updates on this?

**Comment by iDevid** [comment]
@superjd hey man, iOS 13 will get released next week and there is still no fix

**Comment by alexeyvolkov-dev** [comment]
This issue also produces a black screen instead of video content. The sound is playing, but no video. Any ETA when we can get the fix for that?

**Comment by superjd** [comment]
Hi all, Sorry for the delay in responding, we are preparing a new release of the SDK this week, this will address the issue above and other iOS13 related issues we found.

**Comment by iDevid** [comment]
Seems fixed on 4.1.0
