### ISSUE TITLE
SDK 4.1.0 can be used only with Xcode 11

### ISSUE THREAD

**Issue by stopiccot** [AdColony/AdColony-iOS-SDK#58]
Please rebuild 4.1 sdk with Xcode 10 so it can be used in projects that still use Xcode 10.
Currently building with Xcode 10.2.1 gives error: 
```
ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1100.0.33.8.0_0' Reader: '1001.0.46.4_0')', using libLTO version 'LLVM version 10.0.1, (clang-1001.0.46.4)' for architecture armv7
```

**Comment by superjd** [comment]
Hello,
Can you send an email to support@adcolony.com with more details, are you integrating the SDK directly or using something else?

Thanks.
