### ISSUE TITLE
Cannot assign to value: 'setReward' is a method

### ISSUE THREAD

**Issue by mkubo87** [AdColony/AdColony-iOS-SDK#60]
Hello, i'm using Swift 5 on XCode 11 target iOS 11

I get the 
`Cannot assign to value: 'setReward' is a method`

when i write code to configure adcolony

```swift
AdColony.configure(withAppID: "XXXX", zoneIDs: ["XXXX", "XXXX"], options: nil) { [weak self] (zones) in
    for zone in zones {
        if rewardedZones.contains(zone.identifier) {
            // On this line
            zone.setReward = { [weak self] (success, name, amount) in
                if success {
                    self?.rewardUser(coinsAmount: amount, currencyName: name)
                }
            }
        }
    }
}
```

I need this to refresh user rewards

How i can solve it?

**Comment by superjd** [comment]
@mkubo87 Thanks for reporting this, i've updated the documentation with the right usage.
The sample app shows correct usage.

**Comment by mkubo87** [comment]
Hello @superjd i still have the problem with this piece of code
without the "?" i get the 
Cannot assign to value: 'setReward' is a method error
with the "?" i get 
Cannot use optional chaining on non-optional value of type 'AdColonyZone'
